package vn.io.litever.designsystem.theme.palettes

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF535A92)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFDFE0FF)
private val onPrimaryContainerLight = Color(0xFF3B4279)
private val secondaryLight = Color(0xFF5B5D72)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFE0E1F9)
private val onSecondaryContainerLight = Color(0xFF434559)
private val tertiaryLight = Color(0xFF77536C)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFD7F0)
private val onTertiaryContainerLight = Color(0xFF5D3C54)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFBF8FF)
private val onBackgroundLight = Color(0xFF1B1B21)
private val surfaceLight = Color(0xFFFBF8FF)
private val onSurfaceLight = Color(0xFF1B1B21)
private val surfaceVariantLight = Color(0xFFE3E1EC)
private val onSurfaceVariantLight = Color(0xFF46464F)
private val outlineLight = Color(0xFF777680)
private val outlineVariantLight = Color(0xFFC7C5D0)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF303036)
private val inverseOnSurfaceLight = Color(0xFFF2EFF7)
private val inversePrimaryLight = Color(0xFFBCC3FF)
private val surfaceDimLight = Color(0xFFDBD9E0)
private val surfaceBrightLight = Color(0xFFFBF8FF)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFF5F2FA)
private val surfaceContainerLight = Color(0xFFEFEDF4)
private val surfaceContainerHighLight = Color(0xFFE9E7EF)
private val surfaceContainerHighestLight = Color(0xFFE4E1E9)

private val primaryLightMediumContrast = Color(0xFF2A3167)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF6169A2)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF333548)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF6A6C81)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF4B2C43)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF87627B)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFBF8FF)
private val onBackgroundLightMediumContrast = Color(0xFF1B1B21)
private val surfaceLightMediumContrast = Color(0xFFFBF8FF)
private val onSurfaceLightMediumContrast = Color(0xFF101116)
private val surfaceVariantLightMediumContrast = Color(0xFFE3E1EC)
private val onSurfaceVariantLightMediumContrast = Color(0xFF35353E)
private val outlineLightMediumContrast = Color(0xFF52525B)
private val outlineVariantLightMediumContrast = Color(0xFF6C6C76)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF303036)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF2EFF7)
private val inversePrimaryLightMediumContrast = Color(0xFFBCC3FF)
private val surfaceDimLightMediumContrast = Color(0xFFC7C5CD)
private val surfaceBrightLightMediumContrast = Color(0xFFFBF8FF)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFF5F2FA)
private val surfaceContainerLightMediumContrast = Color(0xFFE9E7EF)
private val surfaceContainerHighLightMediumContrast = Color(0xFFDEDCE3)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D0D8)

private val primaryLightHighContrast = Color(0xFF1F275C)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF3D457B)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF292B3D)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF46485C)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF402238)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF603F56)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFBF8FF)
private val onBackgroundLightHighContrast = Color(0xFF1B1B21)
private val surfaceLightHighContrast = Color(0xFFFBF8FF)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFE3E1EC)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF2B2B34)
private val outlineVariantLightHighContrast = Color(0xFF484851)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF303036)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFBCC3FF)
private val surfaceDimLightHighContrast = Color(0xFFBAB8BF)
private val surfaceBrightLightHighContrast = Color(0xFFFBF8FF)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF2EFF7)
private val surfaceContainerLightHighContrast = Color(0xFFE4E1E9)
private val surfaceContainerHighLightHighContrast = Color(0xFFD5D3DB)
private val surfaceContainerHighestLightHighContrast = Color(0xFFC7C5CD)

private val primaryDark = Color(0xFFBCC3FF)
private val onPrimaryDark = Color(0xFF242B61)
private val primaryContainerDark = Color(0xFF3B4279)
private val onPrimaryContainerDark = Color(0xFFDFE0FF)
private val secondaryDark = Color(0xFFC4C5DD)
private val onSecondaryDark = Color(0xFF2D2F42)
private val secondaryContainerDark = Color(0xFF434559)
private val onSecondaryContainerDark = Color(0xFFE0E1F9)
private val tertiaryDark = Color(0xFFE6BAD7)
private val onTertiaryDark = Color(0xFF45263D)
private val tertiaryContainerDark = Color(0xFF5D3C54)
private val onTertiaryContainerDark = Color(0xFFFFD7F0)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF131318)
private val onBackgroundDark = Color(0xFFE4E1E9)
private val surfaceDark = Color(0xFF131318)
private val onSurfaceDark = Color(0xFFE4E1E9)
private val surfaceVariantDark = Color(0xFF46464F)
private val onSurfaceVariantDark = Color(0xFFC7C5D0)
private val outlineDark = Color(0xFF90909A)
private val outlineVariantDark = Color(0xFF46464F)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE4E1E9)
private val inverseOnSurfaceDark = Color(0xFF303036)
private val inversePrimaryDark = Color(0xFF535A92)
private val surfaceDimDark = Color(0xFF131318)
private val surfaceBrightDark = Color(0xFF39393F)
private val surfaceContainerLowestDark = Color(0xFF0D0E13)
private val surfaceContainerLowDark = Color(0xFF1B1B21)
private val surfaceContainerDark = Color(0xFF1F1F25)
private val surfaceContainerHighDark = Color(0xFF29292F)
private val surfaceContainerHighestDark = Color(0xFF34343A)

private val primaryDarkMediumContrast = Color(0xFFD7DAFF)
private val onPrimaryDarkMediumContrast = Color(0xFF182055)
private val primaryContainerDarkMediumContrast = Color(0xFF858DC8)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFDADAF3)
private val onSecondaryDarkMediumContrast = Color(0xFF222437)
private val secondaryContainerDarkMediumContrast = Color(0xFF8E8FA6)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFFDCFED)
private val onTertiaryDarkMediumContrast = Color(0xFF391C32)
private val tertiaryContainerDarkMediumContrast = Color(0xFFAD85A0)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF131318)
private val onBackgroundDarkMediumContrast = Color(0xFFE4E1E9)
private val surfaceDarkMediumContrast = Color(0xFF131318)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF46464F)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFDDDBE6)
private val outlineDarkMediumContrast = Color(0xFFB2B1BB)
private val outlineVariantDarkMediumContrast = Color(0xFF908F99)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE4E1E9)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF29292F)
private val inversePrimaryDarkMediumContrast = Color(0xFF3C447A)
private val surfaceDimDarkMediumContrast = Color(0xFF131318)
private val surfaceBrightDarkMediumContrast = Color(0xFF44444A)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF07070C)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1D23)
private val surfaceContainerDarkMediumContrast = Color(0xFF27272D)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF323238)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF3D3D43)

private val primaryDarkHighContrast = Color(0xFFEFEEFF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFB7BEFD)
private val onPrimaryContainerDarkHighContrast = Color(0xFF000435)
private val secondaryDarkHighContrast = Color(0xFFEFEEFF)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFC0C1D9)
private val onSecondaryContainerDarkHighContrast = Color(0xFF080A1B)
private val tertiaryDarkHighContrast = Color(0xFFFFEBF5)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFE2B6D3)
private val onTertiaryContainerDarkHighContrast = Color(0xFF1A0316)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF131318)
private val onBackgroundDarkHighContrast = Color(0xFFE4E1E9)
private val surfaceDarkHighContrast = Color(0xFF131318)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF46464F)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFF1EFFA)
private val outlineVariantDarkHighContrast = Color(0xFFC3C1CC)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE4E1E9)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF3C447A)
private val surfaceDimDarkHighContrast = Color(0xFF131318)
private val surfaceBrightDarkHighContrast = Color(0xFF504F56)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF1F1F25)
private val surfaceContainerDarkHighContrast = Color(0xFF303036)
private val surfaceContainerHighDarkHighContrast = Color(0xFF3B3B41)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF46464C)

val indigoLightColorScheme: ColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val indigoDarkColorScheme: ColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
