package vn.io.litever.designsystem.theme.palettes

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF855317)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFFFDCBD)
private val onPrimaryContainerLight = Color(0xFF693C00)
private val secondaryLight = Color(0xFF725A42)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFFEDCBE)
private val onSecondaryContainerLight = Color(0xFF59422C)
private val tertiaryLight = Color(0xFF57633A)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFDBE8B5)
private val onTertiaryContainerLight = Color(0xFF404B25)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF8F5)
private val onBackgroundLight = Color(0xFF211A14)
private val surfaceLight = Color(0xFFFFF8F5)
private val onSurfaceLight = Color(0xFF211A14)
private val surfaceVariantLight = Color(0xFFF2DFD1)
private val onSurfaceVariantLight = Color(0xFF50453A)
private val outlineLight = Color(0xFF837568)
private val outlineVariantLight = Color(0xFFD5C3B5)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF372F28)
private val inverseOnSurfaceLight = Color(0xFFFDEEE3)
private val inversePrimaryLight = Color(0xFFFCB974)
private val surfaceDimLight = Color(0xFFE6D7CD)
private val surfaceBrightLight = Color(0xFFFFF8F5)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFFF1E7)
private val surfaceContainerLight = Color(0xFFFAEBE0)
private val surfaceContainerHighLight = Color(0xFFF4E6DA)
private val surfaceContainerHighestLight = Color(0xFFEEE0D5)

private val primaryLightMediumContrast = Color(0xFF512E00)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF966125)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF47321D)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF82684F)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF303A16)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF667248)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF8F5)
private val onBackgroundLightMediumContrast = Color(0xFF211A14)
private val surfaceLightMediumContrast = Color(0xFFFFF8F5)
private val onSurfaceLightMediumContrast = Color(0xFF16100A)
private val surfaceVariantLightMediumContrast = Color(0xFFF2DFD1)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3F342A)
private val outlineLightMediumContrast = Color(0xFF5D5045)
private val outlineVariantLightMediumContrast = Color(0xFF786B5F)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF372F28)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFFDEEE3)
private val inversePrimaryLightMediumContrast = Color(0xFFFCB974)
private val surfaceDimLightMediumContrast = Color(0xFFD2C4BA)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF8F5)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFFF1E7)
private val surfaceContainerLightMediumContrast = Color(0xFFF4E6DA)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE9DACF)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFDDCFC4)

private val primaryLightHighContrast = Color(0xFF432500)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF6C3E01)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF3B2814)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF5B452E)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF26300C)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF424D27)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF8F5)
private val onBackgroundLightHighContrast = Color(0xFF211A14)
private val surfaceLightHighContrast = Color(0xFFFFF8F5)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFF2DFD1)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF352A21)
private val outlineVariantLightHighContrast = Color(0xFF53473C)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF372F28)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFFCB974)
private val surfaceDimLightHighContrast = Color(0xFFC4B6AC)
private val surfaceBrightLightHighContrast = Color(0xFFFFF8F5)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFFDEEE3)
private val surfaceContainerLightHighContrast = Color(0xFFEEE0D5)
private val surfaceContainerHighLightHighContrast = Color(0xFFE0D2C7)
private val surfaceContainerHighestLightHighContrast = Color(0xFFD2C4BA)

private val primaryDark = Color(0xFFFCB974)
private val onPrimaryDark = Color(0xFF492900)
private val primaryContainerDark = Color(0xFF693C00)
private val onPrimaryContainerDark = Color(0xFFFFDCBD)
private val secondaryDark = Color(0xFFE1C1A3)
private val onSecondaryDark = Color(0xFF402C18)
private val secondaryContainerDark = Color(0xFF59422C)
private val onSecondaryContainerDark = Color(0xFFFEDCBE)
private val tertiaryDark = Color(0xFFBFCC9A)
private val onTertiaryDark = Color(0xFF2A3410)
private val tertiaryContainerDark = Color(0xFF404B25)
private val onTertiaryContainerDark = Color(0xFFDBE8B5)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF19120C)
private val onBackgroundDark = Color(0xFFEEE0D5)
private val surfaceDark = Color(0xFF19120C)
private val onSurfaceDark = Color(0xFFEEE0D5)
private val surfaceVariantDark = Color(0xFF50453A)
private val onSurfaceVariantDark = Color(0xFFD5C3B5)
private val outlineDark = Color(0xFF9D8E81)
private val outlineVariantDark = Color(0xFF50453A)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEEE0D5)
private val inverseOnSurfaceDark = Color(0xFF372F28)
private val inversePrimaryDark = Color(0xFF855317)
private val surfaceDimDark = Color(0xFF19120C)
private val surfaceBrightDark = Color(0xFF403830)
private val surfaceContainerLowestDark = Color(0xFF130D07)
private val surfaceContainerLowDark = Color(0xFF211A14)
private val surfaceContainerDark = Color(0xFF261E18)
private val surfaceContainerHighDark = Color(0xFF302921)
private val surfaceContainerHighestDark = Color(0xFF3C332C)

private val primaryDarkMediumContrast = Color(0xFFFFD5AD)
private val onPrimaryDarkMediumContrast = Color(0xFF3A1F00)
private val primaryContainerDarkMediumContrast = Color(0xFFBF8445)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFF8D6B8)
private val onSecondaryDarkMediumContrast = Color(0xFF34220E)
private val secondaryContainerDarkMediumContrast = Color(0xFFA88B71)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFD5E2AF)
private val onTertiaryDarkMediumContrast = Color(0xFF1F2907)
private val tertiaryContainerDarkMediumContrast = Color(0xFF8A9668)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF19120C)
private val onBackgroundDarkMediumContrast = Color(0xFFEEE0D5)
private val surfaceDarkMediumContrast = Color(0xFF19120C)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF50453A)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFEBD9CB)
private val outlineDarkMediumContrast = Color(0xFFC0AFA1)
private val outlineVariantDarkMediumContrast = Color(0xFF9D8E81)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFEEE0D5)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF302921)
private val inversePrimaryDarkMediumContrast = Color(0xFF6A3D00)
private val surfaceDimDarkMediumContrast = Color(0xFF19120C)
private val surfaceBrightDarkMediumContrast = Color(0xFF4C433B)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0C0603)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF231C16)
private val surfaceContainerDarkMediumContrast = Color(0xFF2E261F)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF39312A)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF453C34)

private val primaryDarkHighContrast = Color(0xFFFFEDDE)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFF8B571)
private val onPrimaryContainerDarkHighContrast = Color(0xFF150800)
private val secondaryDarkHighContrast = Color(0xFFFFEDDE)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFDDBDA0)
private val onSecondaryContainerDarkHighContrast = Color(0xFF150800)
private val tertiaryDarkHighContrast = Color(0xFFE9F6C1)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFBBC897)
private val onTertiaryContainerDarkHighContrast = Color(0xFF080D00)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF19120C)
private val onBackgroundDarkHighContrast = Color(0xFFEEE0D5)
private val surfaceDarkHighContrast = Color(0xFF19120C)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF50453A)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFFFEDDE)
private val outlineVariantDarkHighContrast = Color(0xFFD1C0B1)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFEEE0D5)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF6A3D00)
private val surfaceDimDarkHighContrast = Color(0xFF19120C)
private val surfaceBrightDarkHighContrast = Color(0xFF584E46)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF261E18)
private val surfaceContainerDarkHighContrast = Color(0xFF372F28)
private val surfaceContainerHighDarkHighContrast = Color(0xFF433A32)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF4E453D)

val orangeLightColorScheme: ColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val orangeDarkColorScheme: ColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
