package vn.io.litever.designsystem.theme.palettes

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF775084)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFF9D8FF)
private val onPrimaryContainerLight = Color(0xFF5E386A)
private val secondaryLight = Color(0xFF69596C)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFF2DCF3)
private val onSecondaryContainerLight = Color(0xFF514254)
private val tertiaryLight = Color(0xFF82524F)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFFFDAD7)
private val onTertiaryContainerLight = Color(0xFF663B38)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF7FB)
private val onBackgroundLight = Color(0xFF1F1A1F)
private val surfaceLight = Color(0xFFFFF7FB)
private val onSurfaceLight = Color(0xFF1F1A1F)
private val surfaceVariantLight = Color(0xFFEBDFE9)
private val onSurfaceVariantLight = Color(0xFF4C444D)
private val outlineLight = Color(0xFF7D747D)
private val outlineVariantLight = Color(0xFFCFC3CD)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF342F34)
private val inverseOnSurfaceLight = Color(0xFFF8EEF5)
private val inversePrimaryLight = Color(0xFFE6B6F2)
private val surfaceDimLight = Color(0xFFE1D7DE)
private val surfaceBrightLight = Color(0xFFFFF7FB)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFBF1F8)
private val surfaceContainerLight = Color(0xFFF5EBF2)
private val surfaceContainerHighLight = Color(0xFFEFE5ED)
private val surfaceContainerHighestLight = Color(0xFFEAE0E7)

private val primaryLightMediumContrast = Color(0xFF4C2758)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF875E93)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF403143)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF79677C)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF532B29)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF92605D)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF7FB)
private val onBackgroundLightMediumContrast = Color(0xFF1F1A1F)
private val surfaceLightMediumContrast = Color(0xFFFFF7FB)
private val onSurfaceLightMediumContrast = Color(0xFF141015)
private val surfaceVariantLightMediumContrast = Color(0xFFEBDFE9)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3B343C)
private val outlineLightMediumContrast = Color(0xFF585058)
private val outlineVariantLightMediumContrast = Color(0xFF736A73)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF342F34)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF8EEF5)
private val inversePrimaryLightMediumContrast = Color(0xFFE6B6F2)
private val surfaceDimLightMediumContrast = Color(0xFFCDC4CB)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF7FB)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFBF1F8)
private val surfaceContainerLightMediumContrast = Color(0xFFEFE5ED)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE4DAE1)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFD8CFD6)

private val primaryLightHighContrast = Color(0xFF401D4E)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF603A6D)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF352739)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF534457)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF47211F)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF693D3B)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF7FB)
private val onBackgroundLightHighContrast = Color(0xFF1F1A1F)
private val surfaceLightHighContrast = Color(0xFFFFF7FB)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFEBDFE9)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF312A32)
private val outlineVariantLightHighContrast = Color(0xFF4E474F)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF342F34)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFE6B6F2)
private val surfaceDimLightHighContrast = Color(0xFFBFB6BD)
private val surfaceBrightLightHighContrast = Color(0xFFFFF7FB)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF8EEF5)
private val surfaceContainerLightHighContrast = Color(0xFFEAE0E7)
private val surfaceContainerHighLightHighContrast = Color(0xFFDBD2D9)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCDC4CB)

private val primaryDark = Color(0xFFE6B6F2)
private val onPrimaryDark = Color(0xFF452152)
private val primaryContainerDark = Color(0xFF5E386A)
private val onPrimaryContainerDark = Color(0xFFF9D8FF)
private val secondaryDark = Color(0xFFD5C0D7)
private val onSecondaryDark = Color(0xFF3A2C3D)
private val secondaryContainerDark = Color(0xFF514254)
private val onSecondaryContainerDark = Color(0xFFF2DCF3)
private val tertiaryDark = Color(0xFFF5B7B3)
private val onTertiaryDark = Color(0xFF4C2523)
private val tertiaryContainerDark = Color(0xFF663B38)
private val onTertiaryContainerDark = Color(0xFFFFDAD7)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF161217)
private val onBackgroundDark = Color(0xFFEAE0E7)
private val surfaceDark = Color(0xFF161217)
private val onSurfaceDark = Color(0xFFEAE0E7)
private val surfaceVariantDark = Color(0xFF4C444D)
private val onSurfaceVariantDark = Color(0xFFCFC3CD)
private val outlineDark = Color(0xFF988E97)
private val outlineVariantDark = Color(0xFF4C444D)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFEAE0E7)
private val inverseOnSurfaceDark = Color(0xFF342F34)
private val inversePrimaryDark = Color(0xFF775084)
private val surfaceDimDark = Color(0xFF161217)
private val surfaceBrightDark = Color(0xFF3D373D)
private val surfaceContainerLowestDark = Color(0xFF110D12)
private val surfaceContainerLowDark = Color(0xFF1F1A1F)
private val surfaceContainerDark = Color(0xFF231E23)
private val surfaceContainerHighDark = Color(0xFF2D282E)
private val surfaceContainerHighestDark = Color(0xFF383339)

private val primaryDarkMediumContrast = Color(0xFFF7CFFF)
private val onPrimaryDarkMediumContrast = Color(0xFF391646)
private val primaryContainerDarkMediumContrast = Color(0xFFAD81B9)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFEBD6ED)
private val onSecondaryDarkMediumContrast = Color(0xFF2E2132)
private val secondaryContainerDarkMediumContrast = Color(0xFF9D8BA0)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFFFD2CE)
private val onTertiaryDarkMediumContrast = Color(0xFF3F1B19)
private val tertiaryContainerDarkMediumContrast = Color(0xFFBA837F)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF161217)
private val onBackgroundDarkMediumContrast = Color(0xFFEAE0E7)
private val surfaceDarkMediumContrast = Color(0xFF161217)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF4C444D)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFE5D9E3)
private val outlineDarkMediumContrast = Color(0xFFBAAFB8)
private val outlineVariantDarkMediumContrast = Color(0xFF978D97)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFEAE0E7)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D282E)
private val inversePrimaryDarkMediumContrast = Color(0xFF5F396C)
private val surfaceDimDarkMediumContrast = Color(0xFF161217)
private val surfaceBrightDarkMediumContrast = Color(0xFF494348)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF0A060A)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF211C21)
private val surfaceContainerDarkMediumContrast = Color(0xFF2B262C)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF363136)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF423C42)

private val primaryDarkHighContrast = Color(0xFFFEEAFF)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFE1B2EE)
private val onPrimaryContainerDarkHighContrast = Color(0xFF190025)
private val secondaryDarkHighContrast = Color(0xFFFEEAFF)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFD1BCD3)
private val onSecondaryContainerDarkHighContrast = Color(0xFF120716)
private val tertiaryDarkHighContrast = Color(0xFFFFECEA)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFF1B3AF)
private val onTertiaryContainerDarkHighContrast = Color(0xFF1E0303)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF161217)
private val onBackgroundDarkHighContrast = Color(0xFFEAE0E7)
private val surfaceDarkHighContrast = Color(0xFF161217)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF4C444D)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFF9ECF7)
private val outlineVariantDarkHighContrast = Color(0xFFCBBFC9)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFEAE0E7)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF5F396C)
private val surfaceDimDarkHighContrast = Color(0xFF161217)
private val surfaceBrightDarkHighContrast = Color(0xFF544E54)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF231E23)
private val surfaceContainerDarkHighContrast = Color(0xFF342F34)
private val surfaceContainerHighDarkHighContrast = Color(0xFF3F3A3F)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF4B454B)

val violetLightColorScheme: ColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val violetDarkColorScheme: ColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
