package vn.io.litever.designsystem.theme.palettes

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

private val primaryLight = Color(0xFF6D5E0F)
private val onPrimaryLight = Color(0xFFFFFFFF)
private val primaryContainerLight = Color(0xFFF8E287)
private val onPrimaryContainerLight = Color(0xFF534600)
private val secondaryLight = Color(0xFF665E40)
private val onSecondaryLight = Color(0xFFFFFFFF)
private val secondaryContainerLight = Color(0xFFEEE2BC)
private val onSecondaryContainerLight = Color(0xFF4E472A)
private val tertiaryLight = Color(0xFF43664E)
private val onTertiaryLight = Color(0xFFFFFFFF)
private val tertiaryContainerLight = Color(0xFFC5ECCE)
private val onTertiaryContainerLight = Color(0xFF2C4E38)
private val errorLight = Color(0xFFBA1A1A)
private val onErrorLight = Color(0xFFFFFFFF)
private val errorContainerLight = Color(0xFFFFDAD6)
private val onErrorContainerLight = Color(0xFF93000A)
private val backgroundLight = Color(0xFFFFF9EE)
private val onBackgroundLight = Color(0xFF1E1B13)
private val surfaceLight = Color(0xFFFFF9EE)
private val onSurfaceLight = Color(0xFF1E1B13)
private val surfaceVariantLight = Color(0xFFEAE2D0)
private val onSurfaceVariantLight = Color(0xFF4B4739)
private val outlineLight = Color(0xFF7C7767)
private val outlineVariantLight = Color(0xFFCDC6B4)
private val scrimLight = Color(0xFF000000)
private val inverseSurfaceLight = Color(0xFF333027)
private val inverseOnSurfaceLight = Color(0xFFF7F0E2)
private val inversePrimaryLight = Color(0xFFDBC66E)
private val surfaceDimLight = Color(0xFFE0D9CC)
private val surfaceBrightLight = Color(0xFFFFF9EE)
private val surfaceContainerLowestLight = Color(0xFFFFFFFF)
private val surfaceContainerLowLight = Color(0xFFFAF3E5)
private val surfaceContainerLight = Color(0xFFF4EDDF)
private val surfaceContainerHighLight = Color(0xFFEEE8DA)
private val surfaceContainerHighestLight = Color(0xFFE8E2D4)

private val primaryLightMediumContrast = Color(0xFF403600)
private val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
private val primaryContainerLightMediumContrast = Color(0xFF7D6C1E)
private val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryLightMediumContrast = Color(0xFF3C361B)
private val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightMediumContrast = Color(0xFF756D4E)
private val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryLightMediumContrast = Color(0xFF1B3D28)
private val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightMediumContrast = Color(0xFF52755D)
private val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
private val errorLightMediumContrast = Color(0xFF740006)
private val onErrorLightMediumContrast = Color(0xFFFFFFFF)
private val errorContainerLightMediumContrast = Color(0xFFCF2C27)
private val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
private val backgroundLightMediumContrast = Color(0xFFFFF9EE)
private val onBackgroundLightMediumContrast = Color(0xFF1E1B13)
private val surfaceLightMediumContrast = Color(0xFFFFF9EE)
private val onSurfaceLightMediumContrast = Color(0xFF131109)
private val surfaceVariantLightMediumContrast = Color(0xFFEAE2D0)
private val onSurfaceVariantLightMediumContrast = Color(0xFF3A3629)
private val outlineLightMediumContrast = Color(0xFF575244)
private val outlineVariantLightMediumContrast = Color(0xFF726D5E)
private val scrimLightMediumContrast = Color(0xFF000000)
private val inverseSurfaceLightMediumContrast = Color(0xFF333027)
private val inverseOnSurfaceLightMediumContrast = Color(0xFFF7F0E2)
private val inversePrimaryLightMediumContrast = Color(0xFFDBC66E)
private val surfaceDimLightMediumContrast = Color(0xFFCCC6B9)
private val surfaceBrightLightMediumContrast = Color(0xFFFFF9EE)
private val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightMediumContrast = Color(0xFFFAF3E5)
private val surfaceContainerLightMediumContrast = Color(0xFFEEE8DA)
private val surfaceContainerHighLightMediumContrast = Color(0xFFE3DCCF)
private val surfaceContainerHighestLightMediumContrast = Color(0xFFD7D1C4)

private val primaryLightHighContrast = Color(0xFF352C00)
private val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
private val primaryContainerLightHighContrast = Color(0xFF564800)
private val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val secondaryLightHighContrast = Color(0xFF322C12)
private val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
private val secondaryContainerLightHighContrast = Color(0xFF50492D)
private val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryLightHighContrast = Color(0xFF10321F)
private val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
private val tertiaryContainerLightHighContrast = Color(0xFF2E503A)
private val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
private val errorLightHighContrast = Color(0xFF600004)
private val onErrorLightHighContrast = Color(0xFFFFFFFF)
private val errorContainerLightHighContrast = Color(0xFF98000A)
private val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
private val backgroundLightHighContrast = Color(0xFFFFF9EE)
private val onBackgroundLightHighContrast = Color(0xFF1E1B13)
private val surfaceLightHighContrast = Color(0xFFFFF9EE)
private val onSurfaceLightHighContrast = Color(0xFF000000)
private val surfaceVariantLightHighContrast = Color(0xFFEAE2D0)
private val onSurfaceVariantLightHighContrast = Color(0xFF000000)
private val outlineLightHighContrast = Color(0xFF2F2C20)
private val outlineVariantLightHighContrast = Color(0xFF4D493B)
private val scrimLightHighContrast = Color(0xFF000000)
private val inverseSurfaceLightHighContrast = Color(0xFF333027)
private val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
private val inversePrimaryLightHighContrast = Color(0xFFDBC66E)
private val surfaceDimLightHighContrast = Color(0xFFBEB8AB)
private val surfaceBrightLightHighContrast = Color(0xFFFFF9EE)
private val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
private val surfaceContainerLowLightHighContrast = Color(0xFFF7F0E2)
private val surfaceContainerLightHighContrast = Color(0xFFE8E2D4)
private val surfaceContainerHighLightHighContrast = Color(0xFFDAD4C6)
private val surfaceContainerHighestLightHighContrast = Color(0xFFCCC6B9)

private val primaryDark = Color(0xFFDBC66E)
private val onPrimaryDark = Color(0xFF3A3000)
private val primaryContainerDark = Color(0xFF534600)
private val onPrimaryContainerDark = Color(0xFFF8E287)
private val secondaryDark = Color(0xFFD1C6A1)
private val onSecondaryDark = Color(0xFF363016)
private val secondaryContainerDark = Color(0xFF4E472A)
private val onSecondaryContainerDark = Color(0xFFEEE2BC)
private val tertiaryDark = Color(0xFFA9D0B3)
private val onTertiaryDark = Color(0xFF143723)
private val tertiaryContainerDark = Color(0xFF2C4E38)
private val onTertiaryContainerDark = Color(0xFFC5ECCE)
private val errorDark = Color(0xFFFFB4AB)
private val onErrorDark = Color(0xFF690005)
private val errorContainerDark = Color(0xFF93000A)
private val onErrorContainerDark = Color(0xFFFFDAD6)
private val backgroundDark = Color(0xFF15130B)
private val onBackgroundDark = Color(0xFFE8E2D4)
private val surfaceDark = Color(0xFF15130B)
private val onSurfaceDark = Color(0xFFE8E2D4)
private val surfaceVariantDark = Color(0xFF4B4739)
private val onSurfaceVariantDark = Color(0xFFCDC6B4)
private val outlineDark = Color(0xFF969080)
private val outlineVariantDark = Color(0xFF4B4739)
private val scrimDark = Color(0xFF000000)
private val inverseSurfaceDark = Color(0xFFE8E2D4)
private val inverseOnSurfaceDark = Color(0xFF333027)
private val inversePrimaryDark = Color(0xFF6D5E0F)
private val surfaceDimDark = Color(0xFF15130B)
private val surfaceBrightDark = Color(0xFF3C3930)
private val surfaceContainerLowestDark = Color(0xFF100E07)
private val surfaceContainerLowDark = Color(0xFF1E1B13)
private val surfaceContainerDark = Color(0xFF222017)
private val surfaceContainerHighDark = Color(0xFF2D2A21)
private val surfaceContainerHighestDark = Color(0xFF38352B)

private val primaryDarkMediumContrast = Color(0xFFF2DC82)
private val onPrimaryDarkMediumContrast = Color(0xFF2D2500)
private val primaryContainerDarkMediumContrast = Color(0xFFA3903F)
private val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
private val secondaryDarkMediumContrast = Color(0xFFE8DCB6)
private val onSecondaryDarkMediumContrast = Color(0xFF2B250C)
private val secondaryContainerDarkMediumContrast = Color(0xFF9A916F)
private val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
private val tertiaryDarkMediumContrast = Color(0xFFBFE6C8)
private val onTertiaryDarkMediumContrast = Color(0xFF082C18)
private val tertiaryContainerDarkMediumContrast = Color(0xFF75997F)
private val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
private val errorDarkMediumContrast = Color(0xFFFFD2CC)
private val onErrorDarkMediumContrast = Color(0xFF540003)
private val errorContainerDarkMediumContrast = Color(0xFFFF5449)
private val onErrorContainerDarkMediumContrast = Color(0xFF000000)
private val backgroundDarkMediumContrast = Color(0xFF15130B)
private val onBackgroundDarkMediumContrast = Color(0xFFE8E2D4)
private val surfaceDarkMediumContrast = Color(0xFF15130B)
private val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkMediumContrast = Color(0xFF4B4739)
private val onSurfaceVariantDarkMediumContrast = Color(0xFFE3DCCA)
private val outlineDarkMediumContrast = Color(0xFFB8B1A0)
private val outlineVariantDarkMediumContrast = Color(0xFF969080)
private val scrimDarkMediumContrast = Color(0xFF000000)
private val inverseSurfaceDarkMediumContrast = Color(0xFFE8E2D4)
private val inverseOnSurfaceDarkMediumContrast = Color(0xFF2D2A21)
private val inversePrimaryDarkMediumContrast = Color(0xFF554700)
private val surfaceDimDarkMediumContrast = Color(0xFF15130B)
private val surfaceBrightDarkMediumContrast = Color(0xFF48443A)
private val surfaceContainerLowestDarkMediumContrast = Color(0xFF090703)
private val surfaceContainerLowDarkMediumContrast = Color(0xFF201D15)
private val surfaceContainerDarkMediumContrast = Color(0xFF2A281F)
private val surfaceContainerHighDarkMediumContrast = Color(0xFF353229)
private val surfaceContainerHighestDarkMediumContrast = Color(0xFF413D34)

private val primaryDarkHighContrast = Color(0xFFFFF0BA)
private val onPrimaryDarkHighContrast = Color(0xFF000000)
private val primaryContainerDarkHighContrast = Color(0xFFD7C26B)
private val onPrimaryContainerDarkHighContrast = Color(0xFF0F0B00)
private val secondaryDarkHighContrast = Color(0xFFFCF0C9)
private val onSecondaryDarkHighContrast = Color(0xFF000000)
private val secondaryContainerDarkHighContrast = Color(0xFFCDC29E)
private val onSecondaryContainerDarkHighContrast = Color(0xFF0F0B00)
private val tertiaryDarkHighContrast = Color(0xFFD2FADB)
private val onTertiaryDarkHighContrast = Color(0xFF000000)
private val tertiaryContainerDarkHighContrast = Color(0xFFA5CCAF)
private val onTertiaryContainerDarkHighContrast = Color(0xFF000F05)
private val errorDarkHighContrast = Color(0xFFFFECE9)
private val onErrorDarkHighContrast = Color(0xFF000000)
private val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
private val onErrorContainerDarkHighContrast = Color(0xFF220001)
private val backgroundDarkHighContrast = Color(0xFF15130B)
private val onBackgroundDarkHighContrast = Color(0xFFE8E2D4)
private val surfaceDarkHighContrast = Color(0xFF15130B)
private val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
private val surfaceVariantDarkHighContrast = Color(0xFF4B4739)
private val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
private val outlineDarkHighContrast = Color(0xFFF7EFDD)
private val outlineVariantDarkHighContrast = Color(0xFFC9C2B1)
private val scrimDarkHighContrast = Color(0xFF000000)
private val inverseSurfaceDarkHighContrast = Color(0xFFE8E2D4)
private val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
private val inversePrimaryDarkHighContrast = Color(0xFF554700)
private val surfaceDimDarkHighContrast = Color(0xFF15130B)
private val surfaceBrightDarkHighContrast = Color(0xFF535046)
private val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
private val surfaceContainerLowDarkHighContrast = Color(0xFF222017)
private val surfaceContainerDarkHighContrast = Color(0xFF333027)
private val surfaceContainerHighDarkHighContrast = Color(0xFF3E3B32)
private val surfaceContainerHighestDarkHighContrast = Color(0xFF4A473D)

val yellowLightColorScheme: ColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

val yellowDarkColorScheme: ColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
